### ISSUE TITLE
Bug: Version Clash with `nimbus-jose-jwt`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#2302]
# Bug Report

## Describe the Bug
`NoSuchMethodError` messages were observed in MVD that originate in the `JwtUtils` class in EDC, more specifically the `DefaultJWTClaimsVerifier#verify` method.

### Expected Behavior
No error :)

### Observed Behavior
_A clear and concise description of what happened instead._

## Steps to Reproduce
1. attempt to deploy MVD to Azure as per documentation
2. check logs of the registrationservice container

## Context Information
Current Snapshot of all libraries, this only happens when deploying to Azure using the `Cloud-CD.yaml` workflow, because the steps to verify the dataspace deployment are only performed there.

- Used version [e.g. EDC v1.0.0]
- OS: [e.g. iOS, Windows]
- ...

## Detailed Description
Currently the published version catalog specifies to use `com.nimbusds:nimbus-jose-jwt:8.23`. However, some of the libraries we use (e.g. MockServer, Azure Identity) introduce transitive dependencies onto `com.nimbusds:nimbus-jose-jwt:9.2x`.
That particular version contains breaking changes, e.g. in the aforementioned `DefaultJWTClaimsVerifier#verify` method and others.

## Possible Implementation
Perform the following steps in that particular sequence:

- upgrade the version catalog so that it contains `com.nimbusds:nimbus-jose-jwt:9.25`
- in the connector, fix all resulting compile errors and remove the version override

**this means that for some time, the connector builds could be broken! Those two PRs should be merged in quick succession!**

## Subtasks
- [x] Upgrade the VersionCatalog https://github.com/eclipse-edc/GradlePlugins/pull/62
- [x] Upgrade the connector #2294 
- [x] Upgrade the IdentityHub https://github.com/eclipse-edc/IdentityHub/pull/67
