### ISSUE TITLE
Refactor: move technology extensions into their own repo

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#3129]
# Feature Request

This issue serves as umbrella issue to track the refactoring of the technology-specific extensions into their respective repos.

## Which Areas Would Be Affected?
technology extensions

## Why Is the Feature Desired?
Decision Record 2023-03-15 repository split

## Solution Proposal
- [x] eclipse-edc/Connector#3130 
  - [x] eclipse-edc/Connector#3133
  - [x] https://github.com/eclipse-edc/IdentityHub/pull/105
  - [x] https://github.com/eclipse-edc/RegistrationService/pull/95
  - [x] https://github.com/eclipse-edc/FederatedCatalog/pull/115
- [x] eclipse-edc/Connector#3131 
  - [x] eclipse-edc/Connector#3138
- [x] eclipse-edc/Connector#3132
  - [x] eclipse-edc/Connector#3140 
- [x] eclipse-edc/Release#7
