### ISSUE TITLE
Heartbeat from data-plane-selector to dataplane

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#4220]
### What
The data-plane-selector is currently not aware if a dataplane is available or not at the selection, so a transfer could be assigned to a dataplane that's down and the transfer will fail.
To avoid situations like these, the data-plane-selector could set up a state machine where iteratively pings the dataplanes to get their status, that will be used during selection to eventually skip an unavailable/clogged instance.

### TODO
- [x] state machine for data plane instances
- [x] heartbeat that can change data plane instance state
- [x] select functionality to exclude the non-active data plane instances
