### ISSUE TITLE
Feature: Configuration Injection

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#4610]
# Feature Request

Implement a feature that enables _configuration injection_. By annotating certain field values it should be possible to automatically resolve and set config values, for example:

```java
public class SomeExtension extends ServiceExtension {

    @Setting(key = "edc.some.config.value", required = true, defaultValue = "barbaz")
    private String someConfigValue
}
```

thus, `someConfigValue` gets assigned the value of `edc.some.config.value`, or - lacking that - the default value `"barbaz"`. 

In addition, it should be able to group config values together in a _configuration object_, which is basically a POJO:

```java
public class SomeExtension extends ServiceExtension {

    @Configuration
    private SomeConfigObject configObject;

}

public record SomeConfigObject(@Setting(key="...") String stringValue, 
                               @Setting(key="...") Double doubleValue){

}
```

## Which Areas Would Be Affected?

dependency injection, ultimately the entire code base

## Why Is the Feature Desired?

ease of use

## Solution Proposal

enhance the `InjectionPoint` implementations, move some responsibility into the `FieldInjectionPoint` to allow changing the behaviour in other impls.

## Subtasks

- [x] Decision-Record #4611
- [ ] Implementation of the configuration injection (including runtime metamodel and autodoc) 
  - https://github.com/eclipse-edc/Runtime-Metamodel/pull/75
  - https://github.com/eclipse-edc/GradlePlugins/pull/289
  - https://github.com/eclipse-edc/Connector/pull/4617
  - https://github.com/eclipse-edc/Connector/pull/4620
  - https://github.com/eclipse-edc/Connector/pull/4628
- [ ] Adapting the code base to utilize this feature
  - [ ] https://github.com/eclipse-edc/Connector/pull/4633
  - [ ] https://github.com/eclipse-edc/IdentityHub/pull/491
  - [ ] https://github.com/eclipse-edc/FederatedCatalog/pull/265
- [ ] Update the EDC documentation
